#' A set of network events
#'
#' A dataset with network events generated by a mobile device. It is a matrix
#' with 1 column and 198 rows, each row corresponding to one time instant.
#' An element in this matrix represents the antenna ID where the mobile device
#' is connected at each time instant
#'
#' A matrix with 1 column and 198 rows.
#'
#' @docType data
#' @keywords datasets
#' @name events
#' @usage data(events)
#' @format A matrix with 198 rows and 1 column
NULL
